name:                matrix-as-xyz
version:             0.1.1.2
github:              "narumij/matrix-as-xyz"
license:             BSD3
author:              "Jun Narumi"
maintainer:          "narumij@gmail.com"
copyright:           "Jun Narumi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Read and Display representation of matrix like "x,y,z"
category:            Chemistry

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/narumij/matrix-as-xyz#readme>

dependencies:
- base >= 4.8 && < 5
- matrix >= 0.3.5 && < 1
- parsec >= 3.1 && < 4
- hspec >= 2.4 && < 3
- QuickCheck >= 2.4 && < 3

library:
  source-dirs: src

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matrix-as-xyz

  doctest:
    main:                doctests.hs
#    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - matrix-as-xyz
    - doctest
#    - doctest-discover